# Generated by Django 4.0.3 on 2022-04-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=400)),
                ('phone_number', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=300)),
                ('open_hour', models.CharField(max_length=100)),
                ('close_hour', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.3476, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=32.5825, max_digits=9)),
                ('link', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.district')),
            ],
        ),
    ]
